version: '3.10'
services:
  web:
    image: plant-django-image:0.0.1
    build: .
    # command: python manage.py runserver 0.0.0.0:$PORT
    volumes:
      - .:/usr/src/app
    env_file:
      - ./plantdoctor/.env

    expose:
      - 8000

    ports:
      -"$PORT:8000"

    depends_on:
      - tfserving
  tfserving:
    image: tensorflow/serving
    ports:
      - "8501:8501"
    volumes:
      - ./plantdoctor/models_tf:/models/models_tf 
      - ./plantdoctor/models_tf/config:/models/config


    command: --model_config_file=/models/config/models.config

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static:
  
